In [2]:
import torch
import numpy as np

In [1]:
data = [[1,2], [3,4]]

In [3]:
data

[[1, 2], [3, 4]]

In [4]:
x_data = torch.tensor(data)

In [5]:
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
type(x_data)

torch.Tensor

In [7]:
type(data)

list

From another Tensor

In [12]:
x_ones = torch.ones_like(torch.tensor(data))

In [13]:
x_ones

tensor([[1, 1],
        [1, 1]])

From another Tensor but changing the data type

In [14]:
x_ones = torch.ones_like(x_data, dtype=torch.float)

In [15]:
x_ones

tensor([[1., 1.],
        [1., 1.]])

With Random or Constant Values

In [17]:
shape = (2, 3)
shape

(2, 3)

In [20]:
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.9574, 0.1905, 0.1306],
        [0.9760, 0.8190, 0.9470]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


Attributes of a Tensor

In [21]:
tensor = torch.rand(4,4)
tensor

tensor([[0.6364, 0.2306, 0.1441, 0.6721],
        [0.7373, 0.0839, 0.3577, 0.5161],
        [0.9452, 0.4407, 0.4986, 0.3311],
        [0.6247, 0.9318, 0.3968, 0.7638]])

In [22]:
print(f"Shape of the tensor: {tensor.shape}")
print(f"Datatype of the tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of the tensor: torch.Size([4, 4])
Datatype of the tensor: torch.float32
Device tensor is stored on: cpu


Tensor Operations

In [23]:
if torch.accelerator.is_available():
  tensor = tensor.to(torch.accelerator.current_accelerator())

In [24]:
tensor = torch.ones(4,3)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])


Joining Tensors

In [26]:
tensor_2 = torch.zeros(4,3)
tensor_2

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [31]:
two_tensors = torch.cat([tensor, tensor_2], dim=1)
two_tensors

tensor([[1., 0., 1., 0., 0., 0.],
        [1., 0., 1., 0., 0., 0.],
        [1., 0., 1., 0., 0., 0.],
        [1., 0., 1., 0., 0., 0.]])

Arithmetic Operations

In [35]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])

In [38]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

8.0 <class 'float'>


Tensor to Numpy Array

In [41]:
t = torch.ones(5)
print(type(t))
n = t.numpy()
print(type(n))
s = torch.tensor(n)
print(type(s))
w = s.numpy()
print(type(w))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
<class 'torch.Tensor'>
<class 'numpy.ndarray'>
